/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FileDrop {
        /**
          * The id of the an input[type=file] to assign dropped files to
         */
        "target": string;
    }
}
declare global {
    interface HTMLFileDropElement extends Components.FileDrop, HTMLStencilElement {
    }
    var HTMLFileDropElement: {
        prototype: HTMLFileDropElement;
        new (): HTMLFileDropElement;
    };
    interface HTMLElementTagNameMap {
        "file-drop": HTMLFileDropElement;
    }
}
declare namespace LocalJSX {
    interface FileDrop {
        /**
          * The id of the an input[type=file] to assign dropped files to
         */
        "target"?: string;
    }
    interface IntrinsicElements {
        "file-drop": FileDrop;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "file-drop": LocalJSX.FileDrop & JSXBase.HTMLAttributes<HTMLFileDropElement>;
        }
    }
}
